export const teamMembers = [
  {
    id: 1,
    name: "Octavio Consentino",
    role: "FRONTEND DEVELOPER",
    initials: "OC",
    compoundColor: "#E10600",
    photoUrl: "/octa.webp",
    linkedinUrl: "https://www.linkedin.com/in/octavio-cosentino-58a8a12b8/",
  },
  {
    id: 2,
    name: "Mateo Villafañe",
    role: "BACKEND DEVELOPER",
    initials: "MV",
    compoundColor: "#E7B33C",
    photoUrl: "/mate.webp",
    linkedinUrl: "https://www.linkedin.com/in/mateovillafañe/",
  },
  {
    id: 3,
    name: "Martin Mazini",
    role: "FULL STACK DEVELOPER",
    initials: "MM",
    compoundColor: "#F3F1EA",
    photoUrl: "/martin.webp",
    linkedinUrl: "https://www.youtube.com/watch?v=GROgxR27u0Q",
  },
  {
    id: 4,
    name: "Eric Žager",
    role: "ROSSONERO",
    initials: "EZ",
    compoundColor: "#34D399",
    photoUrl: "/eric.webp",
    linkedinUrl: "https://www.linkedin.com/in/zagereric/",
  },
];
